---
- name: Configure Ditto Rust nodes
  hosts: nmxs
  environment:
    BPA_HOST: "{{ lookup('ansible.builtin.env','BPA_HOST') }}"
    NVM_DIR: "{{ ansible_env.HOME }}/.nvm"
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v20.5.1/bin:{{ ansible_env.PATH }}"
  tasks:
    - import_tasks: roles/core.yml
      tags: core
    - import_tasks: roles/rust.yml
      tags: rust
    - import_tasks: roles/node.yml
      tags: node
    - import_tasks: roles/datagen.yml
      tags: datagen

- name: Configure Ditto rPi GPS
  hosts: gps
  environment:
    # NA means this is a no-BPA node
    BPA_HOST: "NA"
    NVM_DIR: "{{ ansible_env.HOME }}/.nvm"
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v20.5.1/bin:{{ ansible_env.PATH }}"
  tasks:
    - import_tasks: roles/core.yml
      tags: core
    - import_tasks: roles/node.yml
      tags: node
    - import_tasks: roles/ditto.yml
      tags: ditto 

- name: Configure Ditto rPi Zeros
  hosts: zeros
  tasks:
    - import_tasks: roles/core.yml
      tags: core
    - import_tasks: roles/node-bin.yml
      tags: node
    - import_tasks: roles/ditto.yml
      tags: ditto 

- name: Configure data generator node
  hosts: datagen
  environment:
    # NA means this is a no-BPA node
    BPA_HOST: "NA"
    NVM_DIR: "{{ ansible_env.HOME }}/.nvm"
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v20.5.1/bin:{{ ansible_env.PATH }}"
  tasks:
    - import_tasks: roles/core.yml
      tags: core
    - import_tasks: roles/node.yml
      tags: node
    - import_tasks: roles/datagen.yml
      tags: datagen

- name: Configure Ditto NetModX Sensor rPis
  hosts: sensor
  environment:
    NVM_DIR: "{{ ansible_env.HOME }}/.nvm"
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v20.5.1/bin:{{ ansible_env.PATH }}"
  tasks:
    - import_tasks: roles/core.yml
      tags: core
    - import_tasks: roles/node.yml
      tags: node
    - import_tasks: roles/ditto.yml
      tags: ditto 

- name: Configure Ditto NetModX Sensor rPis with BPA
  hosts: bpa_sensor
  environment:
    NVM_DIR: "{{ ansible_env.HOME }}/.nvm"
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v20.5.1/bin:{{ ansible_env.PATH }}"
    BPA_HOST: "{{ lookup('ansible.builtin.env','BPA_HOST') }}"
  tasks:
    - import_tasks: roles/core.yml
      tags: core
    - import_tasks: roles/node.yml
      tags: node
    - import_tasks: roles/ditto.yml
      tags: ditto 

- name: Configure NetModX rPis Env
  hosts: rpis
  environment:
    NVM_DIR: "{{ ansible_env.HOME }}/.nvm"
    PATH: "{{ ansible_env.HOME}}/.nvm/versions/node/v20.5.1/bin:{{ ansible_env.PATH }}"
  vars_files:
      - creds.yml
  vars:
    role: receiver
    githubuser: "{{ lookup('env', 'GITHUBUSER') }}"
    githubpassword: "{{ lookup('env', 'GITHUBPASSWORD') }}"
  tasks:
    - import_tasks: roles/core.yml
      tags: core
    - import_tasks: roles/dev.yml
      tags: dev
    #    - import_tasks: roles/docker.yml
      #  tags: docker
    - import_tasks: roles/ditto.yml
      tags: ditto
    # - name: Stop service docker, if started
      # become: true
      # ansible.builtin.service:
        # name: docker
        # state: stopped
        # enabled: false
    - import_tasks: roles/sensor-app.yml
      tags: sensor
    #    - import_tasks: roles/model.yml
      # tags: model_receiver
- name: Configure NetModX Comm Node Env
  hosts: leader
  environment:
    NVM_DIR: "{{ ansible_env.HOME }}/.nvm"
    PATH: "{{ ansible_env.HOME}}/.nvm/versions/node/v20.5.1/bin:{{ ansible_env.PATH }}"
  vars_files:
      - creds.yml
  tasks:
    - import_tasks: roles/core.yml
      tags: core
    - import_tasks: roles/dev.yml
      tags: dev
    - import_tasks: roles/docker.yml
      tags: docker
    - import_tasks: roles/ditto.yml
      tags: ditto
- name: Configure FOB
  hosts: fob
  environment:
    NVM_DIR: "{{ ansible_env.HOME }}/.nvm"
    PATH: "{{ ansible_env.HOME}}/.nvm/versions/node/v20.5.1/bin:{{ ansible_env.PATH }}"
  vars_files:
    - creds.yml
  vars:
    role: "base"
    BROKER_HOST: localhost
    BROKER_PORT: 9092
    USE_BLUETOOTH: false
    USE_LAN: true
  tasks:
    - import_tasks: roles/core.yml
      tags: core
    - import_tasks: roles/dev.yml
      tags: dev
    - import_tasks: roles/docker.yml
      tags: docker
    - import_tasks: roles/redpanda.yml
      tags: redpanda
    - import_tasks: roles/ditto.yml
      tags: ditto
    - import_tasks: roles/collector.yml
      tags: collector
- name: Configure MRZR laptop
  hosts: mrzr
  vars_files:
    - creds.yml
  environment:
    NVM_DIR: "{{ ansible_env.HOME }}/.nvm"
    PATH: "{{ ansible_env.HOME}}/.nvm/versions/node/v20.5.1/bin:{{ ansible_env.PATH }}"
  vars:
    role: "collector"
    BROKER_HOST: localhost
    BROKER_PORT: 9092
    USE_BLUETOOTH: true
    USE_LAN: true
  tasks:
    - import_tasks: roles/core.yml
      tags: core
    - import_tasks: roles/dev.yml
      tags: dev
    - import_tasks: roles/docker.yml
      tags: docker
    - import_tasks: roles/redpanda.yml
      tags: redpanda
    - import_tasks: roles/collector.yml
      tags: collector
    - import_tasks: roles/ditto.yml
      tags: ditto
