- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes
    upgrade: 'yes'
  tags: update

- name: Install Git
  become: true
  apt:
    name: git
    state: present
  tags: install_git
  
- name: Install python3-pip
  become: true
  apt:
    name: python3-pip
    state: present
  tags: install_pip

- name: Install python3-venv
  become: true
  apt:
    name: python3-venv
    state: present
  tags: install_venv

