- name: Clone sensor app repository
  git:
    repo: https://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@github.com/Marco-Christiani/ditto-nmx
    dest: "{{ ansible_user_dir }}/ditto-nmx"
    clone: yes
    update: yes
    force: yes
  register: sensor_install
  tags: sensor-install

- name: Run npm ci
  shell: |
    export NVM_DIR="{{ ansible_user_dir }}/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    cd {{ ansible_user_dir }}/ditto-nmx
    npm i -g typescript
    npm i -g pm2
    npm install --no-progress
    #yarn install
  when: sensor_install.changed
  tags: sensor-install

- name: Place config.js file
  ansible.builtin.template:
    src: templates/sensor_app_config.j2
    dest: "{{ ansible_user_dir }}/ditto-nmx/config.json"
    mode: '0600'
  register: sensor_env
  tags: sensor-install

- name: Run npm run clean-build
  shell: |
    export NVM_DIR="{{ ansible_user_dir }}/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    cd {{ ansible_user_dir }}/ditto-nmx
    rm -rf ./dist
    npm run build
  tags: sensor-install

- name: Start Ditto service if not running
  pm2:
    name: sensor 
    chdir: "{{ ansible_user_dir }}/ditto-nmx"
    script: 'pm2 start --name sensor "npm run start-sense-node -- --listen-for-models true"'
    state: started
  tags: sensor-install 

- name: Setup sensor systemd service
  become: yes
  shell: |
    pm2 startup 
    /home/pi/.nvm/versions/node/v20.5.1/bin pm2 startup systemd -u pi --hp /home/pi
    pm2 save
  args:
    creates: /etc/systemd/system/multi-user.target.wants/pm2-pi.service
  tags: sensor-install 
